#
# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 14
  num_thetas: 512
  resolution: 512
  scale: 128.0
  r: 2.0
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

ectlossconfig: &ref-ectlossconfig
  num_thetas: 512 # Needs to be divisible by 16
  resolution: 512
  scale: 8
  r: 3.0
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  seed: 14

transform: null

data:
  module: datasets.protein_clouds
  root_dir: ./data/cath_npz_split
  batch_size: 16
  num_workers: 0
  pin_memory: True
  seed: 14
  L_max: 500                # must match modelconfig.L_max
  min_len: 128              
  max_len: 500              
  no_scale: False
  scale_by: 100 
  uniform_scale: True
  
trainer: &ref-trainer
  module: trainer
  seed : 1111
  max_epochs: 50000
  log_every_n_steps: 1
  accelerator: auto
  precision: null # TODO: keep? no keep?
  checkpoint_interval: 20
  save_dir: trainer/hamiltonian
  model_name: model.ckpt
  results_dir: ./results

rmsd_modelconfig:
  module: models.fiedler_ordering_model
  L_max: 500 
  learning_rate: 0.0001
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig

cloud_modelconfig:
  module: models.separated_decoder
  L_max: 500 
  learning_rate: 0.0001
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig

logger:
  module: loggers.wandblogger
  project: PointClouds
  entity: mat-bondarev-epfl
  trainconfig: *ref-trainer
  results_dir: fielder_train


